version: 2.1

orbs:
  sonarcloud: extendaretail/sonarcloud@0.0.2

commands:
  build_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t extenda/tech-radar:$CIRCLE_SHA1 .

jobs:
  yamllint:
    docker:
      - image: circleci/python
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Pip install
          command: pip install --user -r .scripts/python_requirements.txt
      - run:
          name: YAML lint
          command: python .scripts/yaml_lint.py
      - run:
          name: Schema validation
          command: python .scripts/yaml_validate.py

  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Lint Javascript
          command: |
            npm run lint:js -- \
              --format junit \
              --output-file test-results/eslint/TEST-eslint.xml
      - run:
          name: Unit tests
          command: npm test -- --ci --runInBand --coverage
      - run:
          name: Build radar
          command: npm run build
      - build_docker
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - test-results
            - coverage

  sonar:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - sonarcloud/scan_with_npm
      - sonarcloud/check_quality_gate

  dockerhub:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Set build version
          command: |
            git config user.name "CircleCI"
            git config user.email "circleci@circleci.com"
            sh .scripts/bump_version.sh
      - run:
          name: Build radar
          command: npm run build
      - build_docker
      - run:
          name: Login on DockerHub
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
      - run:
          name: Deploy to DockerHub
          command: |
            TAG=v$(node -p "require('./package.json').version")
            docker tag extenda/tech-radar:$CIRCLE_SHA1 extenda/tech-radar:$TAG
            docker tag extenda/tech-radar:$CIRCLE_SHA1 extenda/tech-radar:latest
            docker push extenda/tech-radar:$TAG
            docker push extenda/tech-radar:latest

workflows:
  version: 2
  tech_radar:
    jobs:
      - yamllint
      - build:
          requires:
            - yamllint
          filters:
            branches:
              ignore: 'feature/github-actions'
      - sonar:
          context: sonarcloud
          requires:
            - build
          filters:
            branches:
              # Don't run Sonar on forked PRs
              ignore: /^pull\/.*$/
      - dockerhub:
          context: dockerhub
          requires:
            - build
            - sonar
          filters:
            branches:
              only: master
