version: 1
name: Traefik
blip:
  - version: "2.6"
    ring: ASSESS
description: |
  [traefik](https://traefik.io/) is a reverse proxy / load balancer.
rationale:
  We need to look into reverse proxies and load balancers. The product/service should be easy to setup and use regardless of k8s or Docker.
related:
  - name: Nginx
    file: nginx.html
  - name: HAProxy
    file: haproxy.html